### ISSUE TITLE
NSURLSession instead of AlamoFire

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#28]
Hi there,

I'm integrating WistiaKit into a project I'm working on, and I was wondering if it would be possible to use NSURLSession rather than AlamoFire. It seems like AlamoFire is being rather sparingly within the actual project, and since WistiaKit is an SDK, it seems unfortunate to ask for app authors integrate this dependency.

I'd be happy to contribute some time in transitioning it, if there is indeed interest.

Thanks a lot!

**Comment by spinosa** [comment]
Hey @mergesort ,

I've nothing against dropping AF in favor of URLSession.  If you want to work on this, I'd gladly review the PR and get it merged!

**Comment by need2edit** [comment]
@mergesort @spinosa would be happy to contribute here. 

Using NSURLSession with our own internal Wistia Model layer (custom, pre-WistiaKit). Using a very nice "swifty" design pattern where Account, Projects, Medias, Assets, etc all provide typed network resources for consumption by our webservice called 'Wistia'. 

Allows us to: 
a) consolidate all our asynchronous code across our framework to a single method, testing is simple and awesome
b) we do nifty things like this:

`
Wistia.Project.show(id: "123asdfzcx") { result in
   // Do stuff with this project
}

Wistia.Media.show(id: "123asdfzcx") { result in
   // Do stuff with this media
}

Wistia.Project.list(onPage: 5, withLimit: 25) { results in
 // Do stuff with paged / limited project
}
` 

The asynchronous code across all our use cases is the `load` method on the web service.

Inspired by this design:
https://talk.objc.io/episodes/S01E01-networking

@spinosa does this fit into the overall design with WistiaKit?

**Comment by mergesort** [comment]
@need2edit I model my routes a bit differently, separating the route creation from the API calls, but I quite like that design for an API framework. I suppose that question is more aimed to @spinosa.

If you don't mind taking the lead, I wouldn't complain. 😄 
I'll probably be able to get around to it in a couple weeks, that's when I'll start interacting with the API in my work.

Cheers!

**Comment by spinosa** [comment]
@need2edit that is a nice design.  Has a Rails-y feel to it.

Creating model objects within the `Wistia` namespace object (ie. `Wistia.Project`) makes them discoverable within a contained namespace, but slows you down later on (since autocompletion terminates at the `.`).  I prefer keeping the meat at the top level (ie.`WistiaProject`) unless there's a compelling need for the `Wistia` object itself.

Using a generic `Webservice` is nice if you can reuse it between projects, or if it DRYs up / simplifies `WistiaAPI`.  Though the devil may be in the details.  The Wistia Data API (that is, the actual http interface provided by the back end servers) has its share of quirks which show up in API usage and JSON parsing.

Network calls resulting from the use of a model object is common enough these days (ie. `WistiaProject.show(id:)`).  Plenty happens under the covers in CoreData that Apple tries to hide from devs.  There's a certain feel to using a specific API class (ie. `WistiaAPI.showProject(forHash:)`) that I like, but I'm ambivalent and could go either way.

Ultimately for me, this comes down to timing.  While WK is pre-1.0 we can make big changes.  But we want to go 1.0 sooner than later.  While the webservice pattern is nice, I don't think the advantages are sufficient to delay 1.0 release.  Dropping AlamoFire for NSURL can be done at any time, shouldn't impact the API in a major way.

---

So... @need2edit @mergesort if you want to work on part/all of this, I'll be happy to coordinate and get it in the 1.0 (or later, if timing dictates).

---

/cc @jayholman - Since you're working on a nice guide and a sweeping API change would necessarily impact your work, wanted to get your input here, too.
