### ISSUE TITLE
Enable audio with ringer switch turned off

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#40]
Hi again! I'm back with another feature request. Our app is an online school, which means the expectation is for sound to be on when the user starts watching a video.

This below worked, though it might want to be masked.

```
do {
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
} catch(let error) {
    // Handle the error ¯\_(ツ)_/¯
}
```

I can imagine not everyone would want sound to default to on, so my naive solution would be to allow people to externally set the `AVPlaybackCategory`, or hide it behind a boolean such as `canPlaySoundWhenSilentModeEnabled`.

I'd love to hear what we can do to enable this functionality. Happy to contribute with more feedback as needed.

Thanks!

**Comment by spinosa** [comment]
We do the same thing in the official Wistia app (which, of course, uses WistiaKit).

I choose to keep this out of WK since it's an application decision with more complexity than on/off and doesn't seem proper in a lower level framework.  That being said, I do have a TODO to mention this in the README, and will keep this issue open until that's fixed.

**Comment by mergesort** [comment]
Hm, I suppose I can see the logic behind that. The reason I mention it is because users of the main app seem confused that the videos won't play when their ringer is off, since the default behavior in Apple's iOS apps is to play even with the ringer off (see: Safari).

That's just my perspective though, could definitely be wrong. Either way I'll implement it at the app layer for now.

Thanks!
