### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by zocario** [wistia/WistiaKit#43]
We are using Carthage as dependency manager on a big project. Your library doesn't seem to support it as it has no shared framework scheme. Here is the error returned by Carthage:

<img width="853" alt="capture d ecran 2017-02-15 a 09 03 12" src="https://cloud.githubusercontent.com/assets/800617/22965533/3db68c86-f35e-11e6-9aad-8c2b06e6ccbd.png">

Is there any plan on your side to support Carthage?

**Comment by spinosa** [comment]
Hey @zocario 

There are no immediate plans to support Carthage, unfortunately.  But if you'd like to contribute Carthage support as a patch, I'd be happy to help and get it merged!

**Comment by hixfield** [comment]
+1 for carthage support

**Comment by hixfield** [comment]
My cart file:

github "wistia/Wistiakit" ~> 0.30.1

Current build error in carthage:

*** Cloning Wistiakit
*** Checking out Wistiakit at "0.30.1"
*** xcodebuild output can be found in /var/folders/57/0qrd8gt574g9dkdh4sswk6zm0000gn/T/carthage-xcodebuild.Yn2UCY.log
*** Skipped building Wistiakit due to the error:
Dependency "Wistiakit" has no shared framework schemes

Could it be as simple as making the schemes shared?

**Comment by hixfield** [comment]
@spinosa I have made the required changes and submitted a pull request, however I think there is something wrong with the CI because it says the tests have failed but I did not change anything except making the schema's shared.

Can you have a look? 

https://github.com/wistia/WistiaKit/pull/60

**Comment by acj** [comment]
@hixfield There's a known issue with CI that we're looking into, so it's probably not related to your change. I'll take a look at your PR soon. Thanks for your patience!

**Comment by spinosa** [comment]
Carthage supported as of 0.30.2

CI still to be fixed
