### ISSUE TITLE
Thoughts on adding media caching?

### ISSUE THREAD

**Issue by hardythedrummer** [wistia/WistiaKit#46]
I'm looking to write a TvOS app that will loop thru a playlist repeatedly as a form of digital signage in a storefront. Since it's just going to be playing the same videos repeatedly, it makes sense to not download the media every time, but I don't see any way to inject into the player object to cache the media assets manually, nor any options to have WistiaKit do so. Are there any plans to add support for media caching? If not, I'd be willing to work on it myself and submit a PR, but I'd appreciate any guidance on what the best way to accomplish this would be.

**Comment by spinosa** [comment]
hey @hardythedrummer !

As for caching, I absolutely want to see that kind of feature in WK.  My thinking had been to build offline support a la Apple's [playing offline hls](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html).

There are no immediate plans to build this.  If you'd like to do some work, I'd be happy to provide guidance and help throughout the process (design, implementation, feedback, PR, merge).

---

PS As luck would have it, I built a tvOS app using WistiaKit during a Wistia Hackathon last year.  I'll invite you to the repo, it may be interesting to you.  But bear in mind, it's hackathon-quality code and hasn't been updated since =)

**Comment by hardythedrummer** [comment]
Ok, sounds good. I'll fork and start working on it when I get a chance.

**Comment by spinosa** [comment]
Closing this as #55 has been merged and offline playback has been noted as a spec for WistiaKit2.
