### ISSUE TITLE
Wistia background player

### ISSUE THREAD

**Issue by sfkaos** [wistia/WistiaKit#59]
Hello,

I'd like to use the WistiaPlayer in the background via MPRemoteCommandCenter. I noticed that the WistiaKit pod has its own public method - beginHandlingRemoteControlEvents() - to handle the background player but only supports playback of the current track

Is there a way to include next and previous videos as well? All attempts to try to use the AVPlayer that backs the WistiaPlayer to handle this have been fruitless since it does not have access to the URLAsset of the videos.

Any help would be greatly appreciated.

**Comment by spinosa** [comment]
Hey @sfkaos , we would need to use `AVQueuePlayer` instead of `AVPlayer` in WK.  Since it's a subclass, you should be able to drop it in.  Would need to do a little work to allow queueing a video (instead of just replacing), but it shouldn't be too bad.

If you want to fork WK and work on a PR, I'm happy to advise on any API and code changes.  I think this would be useful to many folks!

**Comment by sfkaos** [comment]
Unfortunately, I won't be able to spend any time on it any time soon. But I may be able to come back to this - if you're still willing to help. Thanks!

**Comment by spinosa** [comment]
👍

**Comment by spinosa** [comment]
Closing this for now since it's stale.  Noted as a spec for WistiaKit2.
