### ISSUE TITLE
How to remove full screen in the player?

### ISSUE THREAD

**Issue by bobongski** [wistia/WistiaKit#62]
I would like to remove the full screen in the WistiaFlatPlayerView.

**Comment by acj** [comment]
Thanks for your patience, @bobongski. The WistiaKit player doesn't currently support this, but we're working on it. Our plan is to update the player so that it will respect the options that you've chosen through the Wistia web UI. (The fullscreen button can be disabled via the "Control" menu.)

Related to #64.

**Comment by spinosa** [comment]
@bobongski I am assuming you meant remove fullscreen button in `WistiaPlayerViewController`.  The `WistiaPlayerFlatView` is just a view backed by an `AVPlayerLayer` that we use as a convenience.

Pushing a fix for this shortly.  But note: if you are requesting a `WistiaMedia` from the API, it does not populate the `embedOptions` by default.  You need to explicitly get those, see #72
