### ISSUE TITLE
Usage of dynamic hls m3u8 file

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#8]
I have recently been in contact with wistia support. They have learned met that its now possible to fetch a "dynamic" m3u8 file from wistia that includes all the hls streams. As so called adaptive m3u8. If this one is given to the AVPlayer then following apple docs, the avplayer selects the right bandwidth depending on some algorithme (that I guess olny apple knows). I would suggest using this dynamic m3u8 in wistiakit and let Apple choose the stream instead of doing it ourselves. Given apple guideline 9.4 for app approval this should give us compliancy...? Certainly if an audio onky stream of less then 192kps is included.

**Comment by spinosa** [comment]
This is exactly what we do!  If you init a `WistiaPlayer` or `WistiaPlayerViewController` and set the param `requireHLS=true`, it will only choose an HLS asset (which will be handed to the underlying `AVPlayer`).  Since not all medias have HLS assets yet, this could mean playback will fail.  And since HLS is only required by Apple when video is > 10m on cellular, we do allow for non-hls playback.
